name: build
on:
  push:
    branches:
      - v2.3.0-pre-gen_val_root

jobs:
  build-linux-amd64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Run linter
        run: make venv_lint

      - name: Build for Linux
        run: make build_linux

      - name: Run tests
        run: make venv_test

      - name: Compress the file
        run: |
              export BUILD_FILE_NAME=staking_deposit-cli-linux-amd64;
              mv ./dist/deposit ./${BUILD_FILE_NAME};
              tar -zcvf ${BUILD_FILE_NAME}.tar.gz ${BUILD_FILE_NAME};
              mkdir /tmp/artifacts;
              cp ${BUILD_FILE_NAME}.tar.gz /tmp/artifacts;
              sha256sum ${BUILD_FILE_NAME}.tar.gz | head -c 64 > /tmp/artifacts/${BUILD_FILE_NAME}.sha256
      - uses: actions/upload-artifact@v4
        with:
            name: staking-deposit-cli
            path: /tmp/artifacts/
            if-no-files-found: 'error'

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /tmp/artifacts/staking_deposit-cli-linux-amd64.tar.gz
          asset_name: staking_deposit-cli-linux-amd64
          tag: ${{ github.ref }}
          overwrite: true
          body: "v2.3.0 with lachain config"